packages:
  - "packages/*"
  - "packages/web-ui/example"
  - "packages/coding-agent/examples/extensions/with-deps"
  - "packages/coding-agent/examples/extensions/custom-provider-anthropic"
  - "packages/coding-agent/examples/extensions/custom-provider-gitlab-duo"
<<<<<<< HEAD
  - "packages/coding-agent/examples/extensions/sandbox"
=======
  - "packages/coding-agent/examples/extensions/custom-provider-qwen-cli"
>>>>>>> upstream/main

nodeLinker: hoisted
linkWorkspacePackages: deep
preferWorkspacePackages: true
blockExoticSubdeps: false

onlyBuiltDependencies:
  - "@google/genai"
  - "@parcel/watcher"
  - canvas
  - esbuild
  - koffi
  - protobufjs
